### ISSUE TITLE
`barcode-scan` for current video stream?

### ISSUE THREAD

**Issue by Benjamin-Loison** [vaites/termux-scripts#3]
Hello,

[Your script is limited to a single photo](https://github.com/vaites/termux-scripts/blob/31ab817c6004d71d6e25cd77d4b2488bd22332ee/barcode-scan#L56), are you aware of tools available on termux enabling efficient barcode scanning on the current camera video stream?

Thank you in advance.

**Comment by vaites** [comment]
@Benjamin-Loison, I do not know if there is anything that allows to get a video stream from Termux, but I think is too complex. Didn't needed that because is much easier to use browser-based tools like [QuaggaJS](https://serratus.github.io/quaggaJS/) that you can serve from Termux.

**Comment by Benjamin-Loison** [comment]
https://serratus.github.io/quaggaJS did the trick in my case, thank you for the feedback.
